### create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "fake1@fake.com",
    "password": "abc123"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "fake1@fake.com",
    "password": "abc123"
}

### find a  user with a given ID
GET http://localhost:3000/auth/4

### find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### delete a user with a given ID
DELETE http://localhost:3000/auth/10

### update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "password": "aaa"
}