### create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

### sign in as an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

### get the currently signed in user
GET http://localhost:3000/auth/whoami

### sign out
POST http://localhost:3000/auth/signout

### find a  user with a given ID
GET http://localhost:3000/auth/4

### find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### delete a user with a given ID
DELETE http://localhost:3000/auth/10

### update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "password": "aaa"
}